In [1]:
import torch

In [2]:
modelA = torch.load('yolov8s.pt', map_location=torch.device('cpu'))

In [3]:
state_dict_A = modelA["model"].state_dict()

In [4]:
state_dict_A.keys()

odict_keys(['model.0.conv.weight', 'model.0.bn.weight', 'model.0.bn.bias', 'model.0.bn.running_mean', 'model.0.bn.running_var', 'model.0.bn.num_batches_tracked', 'model.1.conv.weight', 'model.1.bn.weight', 'model.1.bn.bias', 'model.1.bn.running_mean', 'model.1.bn.running_var', 'model.1.bn.num_batches_tracked', 'model.2.cv1.conv.weight', 'model.2.cv1.bn.weight', 'model.2.cv1.bn.bias', 'model.2.cv1.bn.running_mean', 'model.2.cv1.bn.running_var', 'model.2.cv1.bn.num_batches_tracked', 'model.2.cv2.conv.weight', 'model.2.cv2.bn.weight', 'model.2.cv2.bn.bias', 'model.2.cv2.bn.running_mean', 'model.2.cv2.bn.running_var', 'model.2.cv2.bn.num_batches_tracked', 'model.2.m.0.cv1.conv.weight', 'model.2.m.0.cv1.bn.weight', 'model.2.m.0.cv1.bn.bias', 'model.2.m.0.cv1.bn.running_mean', 'model.2.m.0.cv1.bn.running_var', 'model.2.m.0.cv1.bn.num_batches_tracked', 'model.2.m.0.cv2.conv.weight', 'model.2.m.0.cv2.bn.weight', 'model.2.m.0.cv2.bn.bias', 'model.2.m.0.cv2.bn.running_mean', 'model.2.m.0.cv2.bn.

In [5]:
state_dict_A

OrderedDict([('model.0.conv.weight',
              tensor([[[[ 1.4748e-02,  3.1113e-02, -1.3367e-01],
                        [ 8.8623e-02,  9.2712e-02, -1.2421e-02],
                        [-1.0431e-01, -1.1169e-01,  1.3013e-01]],
              
                       [[ 6.9885e-02,  7.8796e-02, -1.2207e-01],
                        [ 7.5134e-02,  9.1614e-02,  2.8954e-03],
                        [-1.9531e-01, -1.5002e-01,  1.5576e-01]],
              
                       [[ 1.9928e-02,  2.0325e-02, -4.2694e-02],
                        [ 3.8910e-02,  4.2053e-02, -2.9678e-02],
                        [-4.9255e-02, -4.5471e-02,  4.4708e-02]]],
              
              
                      [[[ 5.8556e-03, -5.7159e-02, -5.0812e-02],
                        [-9.0210e-02, -2.2900e-01, -2.0544e-01],
                        [-1.1487e-01, -2.4121e-01, -2.1655e-01]],
              
                       [[ 2.6428e-02,  6.1829e-02,  5.2948e-02],
                        [ 5.2673e-02, 

In [6]:
modelB = torch.load('yolov8x.pt', map_location=torch.device('cpu'))

In [7]:
state_dict_B = modelB["model"].state_dict()

In [8]:
state_dict_B.keys()

odict_keys(['model.0.conv.weight', 'model.0.bn.weight', 'model.0.bn.bias', 'model.0.bn.running_mean', 'model.0.bn.running_var', 'model.0.bn.num_batches_tracked', 'model.1.conv.weight', 'model.1.bn.weight', 'model.1.bn.bias', 'model.1.bn.running_mean', 'model.1.bn.running_var', 'model.1.bn.num_batches_tracked', 'model.2.cv1.conv.weight', 'model.2.cv1.bn.weight', 'model.2.cv1.bn.bias', 'model.2.cv1.bn.running_mean', 'model.2.cv1.bn.running_var', 'model.2.cv1.bn.num_batches_tracked', 'model.2.cv2.conv.weight', 'model.2.cv2.bn.weight', 'model.2.cv2.bn.bias', 'model.2.cv2.bn.running_mean', 'model.2.cv2.bn.running_var', 'model.2.cv2.bn.num_batches_tracked', 'model.2.m.0.cv1.conv.weight', 'model.2.m.0.cv1.bn.weight', 'model.2.m.0.cv1.bn.bias', 'model.2.m.0.cv1.bn.running_mean', 'model.2.m.0.cv1.bn.running_var', 'model.2.m.0.cv1.bn.num_batches_tracked', 'model.2.m.0.cv2.conv.weight', 'model.2.m.0.cv2.bn.weight', 'model.2.m.0.cv2.bn.bias', 'model.2.m.0.cv2.bn.running_mean', 'model.2.m.0.cv2.bn.

In [9]:
model_custom = torch.load('last.pt', map_location=torch.device('cpu'))

In [10]:
state_dict_custom = model_custom["model"].state_dict()

In [11]:
state_dict_custom.keys()

odict_keys(['model.0.conv.weight', 'model.0.bn.weight', 'model.0.bn.bias', 'model.0.bn.running_mean', 'model.0.bn.running_var', 'model.0.bn.num_batches_tracked', 'model.1.conv.weight', 'model.1.bn.weight', 'model.1.bn.bias', 'model.1.bn.running_mean', 'model.1.bn.running_var', 'model.1.bn.num_batches_tracked', 'model.2.cv1.conv.weight', 'model.2.cv1.bn.weight', 'model.2.cv1.bn.bias', 'model.2.cv1.bn.running_mean', 'model.2.cv1.bn.running_var', 'model.2.cv1.bn.num_batches_tracked', 'model.2.cv2.conv.weight', 'model.2.cv2.bn.weight', 'model.2.cv2.bn.bias', 'model.2.cv2.bn.running_mean', 'model.2.cv2.bn.running_var', 'model.2.cv2.bn.num_batches_tracked', 'model.2.m.0.cv1.conv.weight', 'model.2.m.0.cv1.bn.weight', 'model.2.m.0.cv1.bn.bias', 'model.2.m.0.cv1.bn.running_mean', 'model.2.m.0.cv1.bn.running_var', 'model.2.m.0.cv1.bn.num_batches_tracked', 'model.2.m.0.cv2.conv.weight', 'model.2.m.0.cv2.bn.weight', 'model.2.m.0.cv2.bn.bias', 'model.2.m.0.cv2.bn.running_mean', 'model.2.m.0.cv2.bn.

In [12]:
for k in list(state_dict_A.keys()):
    if "22" in k and "cv3" in k:
        continue
    state_dict_custom[k] = state_dict_A[k]

In [13]:
state_dict_custom

OrderedDict([('model.0.conv.weight',
              tensor([[[[ 1.4748e-02,  3.1113e-02, -1.3367e-01],
                        [ 8.8623e-02,  9.2712e-02, -1.2421e-02],
                        [-1.0431e-01, -1.1169e-01,  1.3013e-01]],
              
                       [[ 6.9885e-02,  7.8796e-02, -1.2207e-01],
                        [ 7.5134e-02,  9.1614e-02,  2.8954e-03],
                        [-1.9531e-01, -1.5002e-01,  1.5576e-01]],
              
                       [[ 1.9928e-02,  2.0325e-02, -4.2694e-02],
                        [ 3.8910e-02,  4.2053e-02, -2.9678e-02],
                        [-4.9255e-02, -4.5471e-02,  4.4708e-02]]],
              
              
                      [[[ 5.8556e-03, -5.7159e-02, -5.0812e-02],
                        [-9.0210e-02, -2.2900e-01, -2.0544e-01],
                        [-1.1487e-01, -2.4121e-01, -2.1655e-01]],
              
                       [[ 2.6428e-02,  6.1829e-02,  5.2948e-02],
                        [ 5.2673e-02, 

In [14]:
for k in list(state_dict_B.keys()):
    if "22" in k and "cv3" not in k:
        state_dict_custom[k.replace("22", "26")] = state_dict_B[k]
        state_dict_custom[k.replace("22", "30")] = state_dict_B[k]
        state_dict_custom[k.replace("22", "34")] = state_dict_B[k]
        state_dict_custom[k.replace("22", "38")] = state_dict_B[k]

In [15]:
state_dict_B["model.22.cv2.0.0.conv.weight"]

tensor([[[[ 1.9455e-04,  2.7981e-03,  2.3830e-04],
          [-4.6682e-04,  2.0256e-03, -1.4076e-03],
          [-1.1663e-03, -9.4299e-03,  1.3866e-03]],

         [[ 4.5276e-04, -5.9080e-04,  1.0214e-03],
          [ 1.2074e-03,  1.5802e-03,  2.3880e-03],
          [-3.1948e-03, -1.0582e-02, -6.7215e-03]],

         [[ 2.8801e-04, -1.6413e-03, -2.4681e-03],
          [ 9.0837e-04, -1.0979e-04, -6.7949e-04],
          [ 9.6226e-04,  3.8099e-04,  7.6246e-04]],

         ...,

         [[ 1.4877e-04, -2.9011e-03, -8.3256e-04],
          [ 1.8826e-03,  2.7962e-03,  2.0752e-03],
          [ 8.6212e-04, -8.6288e-03, -4.3068e-03]],

         [[ 5.8317e-04,  1.5271e-04,  6.6662e-04],
          [ 1.1377e-03,  1.2131e-03,  3.7785e-03],
          [ 3.1209e-04, -9.4652e-04,  2.2583e-03]],

         [[ 8.6832e-04,  2.3961e-04,  1.4305e-03],
          [ 9.1696e-04,  8.1682e-04, -6.0844e-04],
          [-3.7980e-04,  1.0700e-03, -1.2159e-03]]],


        [[[ 2.3136e-03,  2.2774e-03,  2.8973e-03],
  

In [16]:
state_dict_custom["model.26.cv2.0.0.conv.weight"]

tensor([[[[ 1.9455e-04,  2.7981e-03,  2.3830e-04],
          [-4.6682e-04,  2.0256e-03, -1.4076e-03],
          [-1.1663e-03, -9.4299e-03,  1.3866e-03]],

         [[ 4.5276e-04, -5.9080e-04,  1.0214e-03],
          [ 1.2074e-03,  1.5802e-03,  2.3880e-03],
          [-3.1948e-03, -1.0582e-02, -6.7215e-03]],

         [[ 2.8801e-04, -1.6413e-03, -2.4681e-03],
          [ 9.0837e-04, -1.0979e-04, -6.7949e-04],
          [ 9.6226e-04,  3.8099e-04,  7.6246e-04]],

         ...,

         [[ 1.4877e-04, -2.9011e-03, -8.3256e-04],
          [ 1.8826e-03,  2.7962e-03,  2.0752e-03],
          [ 8.6212e-04, -8.6288e-03, -4.3068e-03]],

         [[ 5.8317e-04,  1.5271e-04,  6.6662e-04],
          [ 1.1377e-03,  1.2131e-03,  3.7785e-03],
          [ 3.1209e-04, -9.4652e-04,  2.2583e-03]],

         [[ 8.6832e-04,  2.3961e-04,  1.4305e-03],
          [ 9.1696e-04,  8.1682e-04, -6.0844e-04],
          [-3.7980e-04,  1.0700e-03, -1.2159e-03]]],


        [[[ 2.3136e-03,  2.2774e-03,  2.8973e-03],
  

In [17]:
model_custom["model"].load_state_dict(state_dict_custom, strict=False)

_IncompatibleKeys(missing_keys=[], unexpected_keys=['model.30.cv2.0.0.conv.weight', 'model.30.cv2.0.0.bn.weight', 'model.30.cv2.0.0.bn.bias', 'model.30.cv2.0.0.bn.running_mean', 'model.30.cv2.0.0.bn.running_var', 'model.30.cv2.0.0.bn.num_batches_tracked', 'model.30.cv2.0.1.conv.weight', 'model.30.cv2.0.1.bn.weight', 'model.30.cv2.0.1.bn.bias', 'model.30.cv2.0.1.bn.running_mean', 'model.30.cv2.0.1.bn.running_var', 'model.30.cv2.0.1.bn.num_batches_tracked', 'model.30.cv2.0.2.weight', 'model.30.cv2.0.2.bias', 'model.30.cv2.1.0.conv.weight', 'model.30.cv2.1.0.bn.weight', 'model.30.cv2.1.0.bn.bias', 'model.30.cv2.1.0.bn.running_mean', 'model.30.cv2.1.0.bn.running_var', 'model.30.cv2.1.0.bn.num_batches_tracked', 'model.30.cv2.1.1.conv.weight', 'model.30.cv2.1.1.bn.weight', 'model.30.cv2.1.1.bn.bias', 'model.30.cv2.1.1.bn.running_mean', 'model.30.cv2.1.1.bn.running_var', 'model.30.cv2.1.1.bn.num_batches_tracked', 'model.30.cv2.1.2.weight', 'model.30.cv2.1.2.bias', 'model.30.cv2.2.0.conv.weigh

In [18]:
torch.save(model_custom, 'yolov8s-custom.pt')

In [19]:
test = torch.load('yolov8s-custom.pt', map_location=torch.device('cpu'))['model'].state_dict().keys()

In [20]:
test

odict_keys(['model.0.conv.weight', 'model.0.bn.weight', 'model.0.bn.bias', 'model.0.bn.running_mean', 'model.0.bn.running_var', 'model.0.bn.num_batches_tracked', 'model.1.conv.weight', 'model.1.bn.weight', 'model.1.bn.bias', 'model.1.bn.running_mean', 'model.1.bn.running_var', 'model.1.bn.num_batches_tracked', 'model.2.cv1.conv.weight', 'model.2.cv1.bn.weight', 'model.2.cv1.bn.bias', 'model.2.cv1.bn.running_mean', 'model.2.cv1.bn.running_var', 'model.2.cv1.bn.num_batches_tracked', 'model.2.cv2.conv.weight', 'model.2.cv2.bn.weight', 'model.2.cv2.bn.bias', 'model.2.cv2.bn.running_mean', 'model.2.cv2.bn.running_var', 'model.2.cv2.bn.num_batches_tracked', 'model.2.m.0.cv1.conv.weight', 'model.2.m.0.cv1.bn.weight', 'model.2.m.0.cv1.bn.bias', 'model.2.m.0.cv1.bn.running_mean', 'model.2.m.0.cv1.bn.running_var', 'model.2.m.0.cv1.bn.num_batches_tracked', 'model.2.m.0.cv2.conv.weight', 'model.2.m.0.cv2.bn.weight', 'model.2.m.0.cv2.bn.bias', 'model.2.m.0.cv2.bn.running_mean', 'model.2.m.0.cv2.bn.